@startuml inline_umlgraph_1.svg
          addAck() + isAckAcknowledged() + getRequestedAckStatuses() + deleteAckFromList() + run() + getAckListSize()
          + getAckList() + getCurrentAckValue() }
@enduml
@startuml inline_umlgraph_2.svg
class RequestBodyCleaner {
  + cleanAckRequestBody()
}

note right of RequestBodyCleaner
Responsibilities:
- Formats bodies of Requests by removing channel field
Collaborators:
end note
@enduml
@startuml inline_umlgraph_3.svg
class HeaderInfo {
  + asSDElement()
}

HeaderInfo --> Converter : SDElement of HTTP headers

XForwardedFor --> HeaderInfo : Information about this HTTP header
XForwardedHost --> HeaderInfo : Information about this HTTP header
XForwardedProto --> HeaderInfo : Information about this HTTP header

note right of HeaderInfo
Responsibilities:
- Provide SDElement of HTTP headers

Collaborators:
- XForwardedFor
- XForwardedHosts
- XForwardedProto
- SDElement

end note
@enduml
@startuml inline_umlgraph_4.svg
class XForwardedForImpl {
  + isStub()
  + value()
}

XForwardedForImpl --> HeaderInfo : Value of the HTTP header

note right of XForwardedForImpl
Responsibilities:
- Provide value of the HTTP header
- Tell others that it is not a stub object

Collaborators:
- HeaderInfo

end note
@enduml
@startuml inline_umlgraph_5.svg
class XForwardedForStub {
  + isStub()
  + value()
}

XForwardedForStub --> HeaderInfo : Tell that it is a stub

note right of XForwardedForStub
Responsibilities:
- Throw an exception if value is asked for
- Tell others that it is a stub object

Collaborators:
- HeaderInfo

end note
@enduml
@startuml inline_umlgraph_6.svg
class XForwardedHostImpl {
  + isStub()
  + value()
}

XForwardedHostImpl --> HeaderInfo : Value of the HTTP header

note right of XForwardedHostImpl
Responsibilities:
- Provide value of the HTTP header
- Tell others that it is not a stub object

Collaborators:
- HeaderInfo

end note
@enduml
@startuml inline_umlgraph_7.svg
class XForwardedHostStub {
  + isStub()
  + value()
}

XForwardedHostStub --> HeaderInfo : Tell that it is a stub

note right of XForwardedHostStub
Responsibilities:
- Throw an exception if value is asked for
- Tell others that it is a stub object

Collaborators:
- HeaderInfo

end note
@enduml
@startuml inline_umlgraph_8.svg
class XForwardedProtoImpl {
  + isStub()
  + value()
}

XForwardedProtoImpl --> HeaderInfo : Value of the HTTP header

note right of XForwardedProtoImpl
Responsibilities:
- Provide value of the HTTP header
- Tell others that it is not a stub object

Collaborators:
- HeaderInfo

end note
@enduml
@startuml inline_umlgraph_9.svg
class XForwardedProtoStub {
  + isStub()
  + value()
}

XForwardedProtoStub --> HeaderInfo : Tell that it is a stub

note right of XForwardedProtoStub
Responsibilities:
- Throw an exception if value is asked for
- Tell others that it is a stub object

Collaborators:
- HeaderInfo

end note
@enduml
@startuml inline_umlgraph_10.svg
class HECRestController {
  + sendEvents()
  + sendEvents()
  + getAcksWithPostMethod()
  + getAcks()
  + sendEventsWithFormatOption()
  + sendEventsWithFormatOption()
  + sendEventsWithProtocolVersion()
  + getHealth()
  + getHealthWithProtocolVersion()
  + sendMintData()
  + sendMintDataWithProtocolVersion()
  + sendRawData()
  + sendRawDataWithProtocolVersion()
}

HECRestController --> HECService : Delegation of requests
HECRestController --> RequestBodyCleaner : Formatting of requests

note right of HECRestController
Responsibilities:
 - Implements REST API endpoints.
 - Accepts HTTPServlet reqeuests.
 - Cleans Requests via RequestBodyCleaner and delegates them to HECService
 - Logs the time elapsed while handling requests.

Collaborators:
- RequestBodyCleaner
- HECService
end note
@enduml
@startuml inline_umlgraph_11.svg
interface HECService {
  sendEvents()
  getAcks()
  healthCheck()
}

HECRestController --> HECService : Sends formatted Requests
HECService --> HECServiceImpl : Implements interface

note right of HECService
Responsibilities:
- Defines interface for functionality of HECRestController endpoints
- Defines interface for a health check
- Defines interface for getting Acks for a Channel

Collaborators:
- HECServiceImpl
end note
@enduml
