@startuml inline_umlgraph_1.svg
          addAck() + isAckAcknowledged() + getRequestedAckStatuses() + deleteAckFromList() + run() + getAckListSize()
          + getAckList() + getCurrentAckValue() }
@enduml
@startuml inline_umlgraph_2.svg
  + cleanAckRequestBody(String body, String channel)
}

note right of RequestBodyCleaner
Responsibilities:
- Formats bodies of Requests by removing channel field
Collaborators:
end note
@enduml
@startuml inline_umlgraph_3.svg
class HeaderInfo {
  + asSDElement()
}

HeaderInfo --> Converter : SDElement of HTTP headers

XForwardedFor --> HeaderInfo : Information about this HTTP header
XForwardedHost --> HeaderInfo : Information about this HTTP header
XForwardedProto --> HeaderInfo : Information about this HTTP header

note right of HeaderInfo
Responsibilities:
- Provide SDElement of HTTP headers

Collaborators:
- XForwardedFor
- XForwardedHosts
- XForwardedProto
- SDElement

end note
@enduml
@startuml inline_umlgraph_4.svg
}

HECRestController --> HECService : Delegation of requests
HECRestController --> RequestBodyCleaner : Formatting of requests

note right of HECRestController
Responsibilities:
 - Implements REST API endpoints.
 - Accepts HTTPServlet reqeuests.
 - Cleans Requests via RequestBodyCleaner and delegates them to HECService
 - Logs the time elapsed while handling requests.

Collaborators:
- RequestBodyCleaner
- HECService
end note
@enduml
