@startuml inline_umlgraph_1.svg
          addAck() + isAckAcknowledged() + getRequestedAckStatuses() + deleteAckFromList() + run() + getAckListSize()
          + getAckList() + getCurrentAckValue() }
@enduml
@startuml inline_umlgraph_2.svg
class HeaderInfo {
  + asSDElement()
}

HeaderInfo --> Converter : SDElement of HTTP headers

XForwardedFor --> HeaderInfo : Information about this HTTP header
XForwardedHost --> HeaderInfo : Information about this HTTP header
XForwardedProto --> HeaderInfo : Information about this HTTP header

note right of HeaderInfo
Responsibilities:
- Provide SDElement of HTTP headers

Collaborators:
- XForwardedFor
- XForwardedHosts
- XForwardedProto
- SDElement

end note
@enduml
@startuml inline_umlgraph_3.svg
}
@enduml
